dubbo:
  application:
    logger: slf4j
    name: MsgPushApplication
  registry:
#    address: zookeeper://${zookeeper.address:127.0.0.1}:2181
    address: nacos://${nacos.address:localhost}:8848?username=nacos&password=nacos
  config-center:
    address: nacos://${nacos.address:localhost}:8848?username=nacos&password=nacos
  protocol:
    name: tri
    port: 50051

nacos:
  config:
    server-addr: ${austin.nacos.address:localhost}:8848
    type: yaml
    data-id: user-center-dtp-dev.yml
    auto-refresh: true
    username: ${austin.nacos.username:nacos}
    password: ${austin.nacos.password:nacos}
    group: DEFAULT_GROUP
    bootstrap:
      enable: true
      log-enabled: true

management:
  metrics:
    export:
      prometheus:
        enabled: true
  server:
    port: 29999 # 可选配置，如果不配置该 port，直接使用 ${server.port}
  endpoints:
    web:
      exposure:
        include: '*' # 测试使用，开启了所有端点，生产环境不建议 *
#spring:
#  dynamic:
#    thread-pool:
#      server-addr: http://localhost:6691
#      username: admin
#      password: 123456
#      namespace: prescription
#      monitor:
#        enable: true # 是否开启采集线程池运行时数据
#        collect-interval: 5000 # 采集线程池运行数据频率
#        collect-types: server,micrometer # 采集线程池运行数据的类型。eg：server、micrometer。多个可以同时使用，默认 server
#        initial-delay: 10000 # 项目启动后延迟多久进行采集
#        thread-pool-types: dynamic # 采集线程池的类型。eg：dynamic、web、adapter。可任意配置，默认 dynamic

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/austin?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: root123_A
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver





