server.port=18086

spring.application.name=springboot3

# 启用 HTTP/2 支持
server.http2.enabled=true

# SSL/HTTPS 配置
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=changeit
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=tomcat
